
get http://localhost:8000/pets

###
post http://localhost:8000/addPet
Content-Type: application/json
Accept: application/json

  {
    "type": "Dog",
    "name": "testForTest",
    "adoption_status": "Available",
    "picture": "https://images.squarespace-cdn.com/content/5c52811f1137a633536d811e/1588448958214-MUJZVHNJ7FXYLPXHSMWO/Homeward+Bound+Shadow.jpg?format=1500w&content-type=image%2Fjpeg",
    "height": "40cm",
    "weight": "2.5 kg",
    "color": "off white",
    "bio": "Male",
    "hypoallergenic": "true",
    "age": 9,
    "breed": "golden",
    "dietary_restrictions": "no fish",
    "owner": "64033c73b374207b7e32f7ac"
  }

###

post http://localhost:8000/login
Content-Type: application/json

  {
    "email": "a@a.com",
    "password": "1234"
  }
###
get http://localhost:8000/pet/user/64033c73b374207b7e32f7ac
###
get http://localhost:8000/pets
###
get http://localhost:8000/pet/63f9f711b2ac0c536433a982
Content-Type: application/json
###
put http://localhost:8000/pet/63f9f711b2ac0c536433a982
Content-Type: application/json

{
  "name": "Chance",
  "type": "Dog",
  "breed": "American Bulldog",
  "age": 4,
  "adoption_Status": "Available",
  "height": "40cm",
  "color": "off white",
  "bio": "bio"
}

###
post http://localhost:8000/pet
Content-Type: application/json

{
  "weight": {
    "min": 0,
    "max": 10
  },
  "type": ["dog", "cat"]
}
###
post http://localhost:8000/pet/ :id/adopt
###
post http://localhost:8000/pet/ :id/return
###
post http://localhost:8000/pet/:id/save
###
delete http://localhost:8000/pet/ :id/save
###

